---
- name: Instalare pachet MariaDB Server
  apt:
    name: mariadb-server
    state: present

- name: Ensure /var/log/mysql directory exists for binary logs
  file:
    path: /var/log/mysql
    state: directory
    owner: mysql
    group: mysql
    mode: '0755'

- name: Adaugare configuratie de Master pentru replicare
  template:
    src: 99-replication.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/99-replication.cnf
  notify: Restart MariaDB

- name: Asigurare ca serviciul MariaDB este pornit
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Creare user pentru replicare
  mysql_user:
    name: "{{ repl_user }}"
    password: "{{ repl_password }}"
    priv: "*.*:REPLICATION SLAVE"
    host: "%"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

